### ISSUE TITLE
fail to build on vs2015

### ISSUE THREAD

**Issue by PinkD** [TunSafe/TunSafe#1]
Type:
- build error

OS: 
- Win7

Compiler: 
- VS2015

Code:
- [code1](https://github.com/TunSafe/TunSafe/blob/master/network_win32.cpp#L956)
- [code2](https://github.com/TunSafe/TunSafe/blob/master/network_win32.cpp#L1021)
- [code3](https://github.com/TunSafe/TunSafe/blob/master/wireguard_config.cpp#L24)

Issue:
- parameter type doesn't match

Solution:
- `(void *)` should be added for the second param

btw, the stable version `TunSafe 1.2` on the website doesn't support command line options while newest source code version supports.

**Comment by strigeus** [comment]
Fixed in master
