### ISSUE TITLE
Bring back internet kill switch to previous state on disconnect

### ISSUE THREAD

**Issue by bykidi** [TunSafe/TunSafe#12]
Issue name.
For example, you got blockinternet=route in your config.
Before connecting you had your direct connection to the network.
Connected - kill switch activated.
Disconnected - kill switch stays activated. Should switch back to previous state (disable if it was disabled and such)
Tested on RC1, gonna try on 1.4 release

**Comment by bykidi** [comment]
yup. still the same on 1.4 release. a bit annoying.
if you put your config to the client's machine, they disconnect and breaking my phone with the question "why is my internet not working anymore?!?!?!" :)

**Comment by PinkD** [comment]
`your phone`? what's your device? Android? maybe you should provide more information

**Comment by bykidi** [comment]
common windows 1809 x64 installation

**Comment by strigeus** [comment]
This is being fixed in 1.5-rc1. Will release that in a couple of days.

**Comment by bykidi** [comment]
Thanks. Also can you please add an example of 'ExcludedIPs' to the manual?
