### ISSUE TITLE
work on Mac not well

### ISSUE THREAD

**Issue by xiyionxiong** [TunSafe/TunSafe#19]
build:
`sudo sh ./build_osx.sh
  adding: tunsafe (deflated 58%)
  adding: readme_osx.txt (deflated 29%)
`
run with sudo 
`sudo tunsafe start -d TunSafe.conf
sudo: tunsafe: command not found`
run 

`tunsafe start -d TunSafe.conf
Loading file: TunSafe.conf
Error opening tun device`

**Comment by luofeng0603** [comment]
I have the same question

**Comment by strigeus** [comment]
sudo ./tunsafe start -d TunSafe.conf

**Comment by RealLau** [comment]
can not agree more @strigeus
