### ISSUE TITLE
Example config contains insecure defaults

### ISSUE THREAD

**Issue by notr1ch** [TunSafe/TunSafe#23]
On Windows, the sample configuration file (TunSafe.conf) contains a hard-coded private key. The config file doesn't warn the user to change it, and the comment next to the key calls it "The private key of this computer" which users might interpret as the installer having created a secure random key for them.

As the security of WireGuard depends on secret keys, this default is insecure. I would suggest one of the following, in order of preference:

- Generate cryptographically secure random keys on installation and use them in the sample configuration file.
- Remove the example keys from the config file and instruct users on how to use the key generation feature.
- Refuse to start if a key matches the hard-coded default.
- Add scary warning text in the sample config comments informing users that they must replace the key for security.

**Comment by Telmesomething** [comment]
Where do you see that? In the UI --> Advanced tab only the public key shows. 

You might want to try creating a new configuration file which is based nearer to your location: https://forum.tunsafe.com/viewtopic.php?id=21

**Comment by notr1ch** [comment]
Closing as the project seems dead.
