### ISSUE TITLE
Cannot put comments after DNS field

### ISSUE THREAD

**Issue by Chocobo1** [TunSafe/TunSafe#4]
If I put the following in .conf file
```
DNS = 8.8.8.8  # won't work
```
it results in:
```
[21:13:23] Unable to resolve 8.8.8.8  # won't work. Trying again in 1 second(s)
```

TunSafe 1.4-rc1 x64 on Windows.
It would be nice if TunSafe can ignore the comments properly.

**Comment by strigeus** [comment]
Will fix

**Comment by strigeus** [comment]
Fixed in master
