### ISSUE TITLE
build_linux.sh does not work at all with Fedora-29 and clang

### ISSUE THREAD

**Issue by MystesofEternity** [TunSafe/TunSafe#45]
Tried to follow and execute instructions at: [https://tunsafe.com/user-guide/linux](url)
On Fedora-29. Installed clang on it which got me the clang-7.0.1-4

Also modified build_linux.sh to supposedly work on this version of clang by changing "clang++-6.0" to just "clang"

After executing make, I got a hugeass log of errors and I attached it to this issue for your analysis.
[compile errors.txt](https://github.com/TunSafe/TunSafe/files/2969933/compile.errors.txt)

I suppose I'll try to get and use the version 6 of clang for the sake of making it work, and hopefully it does work. If ever it also doesn't work, I suppose I'll reply to this issue thread along with errors/problems that I'll get.

**Comment by floating-cat** [comment]
Try to use `clang++` instead of `clang`.

**Comment by MystesofEternity** [comment]
That really solved the problem
Good grief so clang is for c while clang++ is for c++? Hahaha figures
Thank you very much for that

**Comment by ghost** [comment]
why are you forcing use of clang... default in Fedora is gcc
cc -v
Using built-in specs.
COLLECT_GCC=/bin/cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20190223 (Red Hat 8.3.1-2) (GCC) 
[root@localhost TunSafe]# cat build_linux.sh 
#!/bin/sh
set -e

RELARGS="-O3 -DNDEBUG"
DBGARGS="-g -D_DEBUG"
CURARGS="$RELARGS"

c++ -c -march=skylake-avx512 crypto/poly1305/poly1305-x64-linux.s crypto/chacha20/chacha20-x64-linux.s
c++ -I . $CURARGS -DWITH_NETWORK_BSD=1 -mssse3 -pthread -lrt -o tunsafe \
tunsafe_amalgam.cpp \
crypto/aesgcm/aesni_gcm-x64-linux.s \
crypto/aesgcm/aesni-x64-linux.s \
crypto/aesgcm/ghash-x64-linux.s \
chacha20-x64-linux.o \
poly1305-x64-linux.o \
[root@localhost TunSafe]# gmake clean
gmake: *** No rule to make target 'clean'.  Stop.
[root@localhost TunSafe]# make clean
make: *** No rule to make target 'clean'.  Stop.
[root@localhost TunSafe]# make
sh ./build_linux.sh
ls -al tunsafe
-rwxr-xr-x. 1 root root 340728 Mar 28 12:09 tunsafe

works fine......

**Comment by MystesofEternity** [comment]
I think it's gonna be good to make a pull request of that to remove clang as pre-requisite
Though it may also be good to hear them out as to why they had to depend and use clang++
