### ISSUE TITLE
TunSafe doesn't restore IPv6 settings

### ISSUE THREAD

**Issue by Chocobo1** [TunSafe/TunSafe#5]
TunSafe doesn't restore interface's previous IPv6 settings after disconnecting from server:
(images found on the net)
![IPv6 settings img](http://myhken.info/div/080515ipv6_003.jpg)
![Advanced settings img](https://wiretuts.com/wp-content/uploads/2015/07/windows-7-network-advanced-tcp-ip-settings.jpg)

The original settings was "Obtain an IPv6 address automatically" & "Obtain DNS server address automatically" & "Automatic metric".

**Comment by strigeus** [comment]
How should TunSafe do this ... if the computer abruply reboots TunSafe will have no chance of restoring the old settings because those are not remembered unless TunSafe maybe could store them in the registry.... Sounds like a can of worms :(

**Comment by Chocobo1** [comment]
Hmm, I am having limited view on all the program possible usages, but at least I think it would be just sufficient to restore it when user click the disconnection button.

**Comment by strigeus** [comment]
Fixed in master. It restores the old address now.
