### ISSUE TITLE
Multiple DNS not allowed.

### ISSUE THREAD

**Issue by MrSorcus** [TunSafe/TunSafe#6]
```
Error parsing [Interface].DNS = 2606:4700:4700::1001
```
But in wg-quick man `DNS — a comma-separated list of IP (v4 or v6) addresses to be set as the interface's DNS servers.`

Version: 1.4-rc1

**Comment by francisuk1989** [comment]
IPv6 address wont work nor IPv6 DNS at the moment
https://github.com/TunSafe/TunSafe/issues/5

**Comment by strigeus** [comment]
Fixed in master. Now you can have 4 DNS servers
