### ISSUE TITLE
Compiler Error on Raspberry Pi 4

### ISSUE THREAD

**Issue by testo94** [TunSafe/TunSafe#66]
I tried to compile TunSafe for my Raspberry Pi but while running build_linux.sh, I receive the following error:

clang: error: the clang compiler does not support '-march=skylake-avx512'

**Comment by testo94** [comment]
Okay I fixed it, you have to Edit the Makefile and install g++-6
Makefile:
ifeq ($(UNAME), Linux)
tunsafe:
	sh ./build_linux_rpi.sh
endif

**Comment by hats00n** [comment]
i had the same problem. but after taking above suggestion saw that g++-6 wasn't available , so i took g++-7 and opened the 
build_linux_rpi.sh file and removed `-6` from g++ . then i faced this: 

```
/usr/bin/ld: /tmp/ccev9pNV.o: in function `SignalCatcher::SignalCatcher(bool*, bool*)':
/root/tunsafe/TunSafe/tunsafe_bsd.cpp:625: undefined reference to `timer_create'
/usr/bin/ld: /root/tunsafe/TunSafe/tunsafe_bsd.cpp:630: undefined reference to `timer_settime'
```
for resolving this , open the build_linux_rpi.sh and at -lrt flag at the very end:
```
#!/bin/sh

set -e
#cpp -D__ARM_ARCH__=7 crypto/chacha20/chacha20-arm.s > crypto/chacha20/chacha20-arm.preprocessed.s
#cpp -D__ARM_ARCH__=7 crypto/poly1305/poly1305-arm.s > crypto/poly1305/poly1305-arm.preprocessed.s

g++ -mfpu=neon  -I . -g -O2 -DNDEBUG -DWITH_NETWORK_BSD=1 -fno-omit-frame-pointer -march=armv7-a -mthumb -std=c++11 -pthread -lrt -o tunsafe \
tunsafe_amalgam.cpp \
crypto/chacha20/chacha20-arm-linux.S \
crypto/poly1305/poly1305-arm-linux.S  -lrt\
```
hope it saves someone's time.
